language: R
sudo: false
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

pandoc_version: 2.1.1

env:
  global:
    - secure: J_1mz-9jIygYbAOjmcHoiQ

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
