language: R
sudo: true
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

pandoc_version: 2.2.1

env:
  global:
    - secure: J_1mz-9jIygYbAOjmcHoiQ

repos:
  CRAN: https://cloud.r-project.org

branches:
  only:
  - master

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - sudo tlmgr update --self
  - sudo tlmgr install unicode-math
  - sudo tlmgr install filehook
  - sudo tlmgr install lm-math


script:
  - ./_build.sh
  - ./_deploy.sh

notifications:
  email:
    recipients:
      - brucezhaor@163.com
    on_success: change
    on_failure: always
